/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GeradorDeSenha;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.security.SecureRandom;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import org.apache.commons.mail.EmailAttachment;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.MultiPartEmail;
import java.awt.Cursor;

/**
 *
 * @author tecnico.daniel
 */
public class tela1 extends javax.swing.JFrame {

    /**
     * Creates new form tela1
     */
    public tela1() {
        initComponents();

        //(
        //acão para quando estiver no txtmatricula e todos os campos tiverem preenchidos e clicar no enter ele preceguirá
        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1.doClick();
                }

            }
        });

        //acão para quando estiver no txtemail e todos os campos tiverem preenchidos e clicar no enter ele preceguirá
        jTextField2.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1.doClick();
                }

            }
        });

        //acão para quando estiver no button e todos os campos tiverem preenchidos e clicar no enter ele preceguirá
        jButton1.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1.doClick();
                }

            }
        });

        //) criará ação ao estiver em determinado campo e pressionar o enter

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Youpasswordmail");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Matrícula Windows:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("E-mail para envio:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar senha");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("By Daniel Vitório Augusto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String matricula = jTextField1.getText();
        String emailConsultor = jTextField2.getText();
        Cursor cursor = new Cursor(Cursor.WAIT_CURSOR);
        jButton1.setCursor(cursor); //setará o botão quando estiver carregando

        LocalDate dataAtual = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataFormatada = dataAtual.format(formatter);//formatando e registrando a data

        String senhaAleatoria = gerarSenhaAleatoria();

        try {

            if (!emailConsultor.equals("") && !matricula.equals("") && (emailConsultor.endsWith("@seuprovedor.com") || emailConsultor.endsWith("@seuprovedor.com.br"))) {//Não permitirá a mensagen ser enviada para outro email que não seja  seuprovedor.com ou seuprovedor.com.br, e não procegurá com a troca de senha se o campo estiver vazio

                
                // Cria o processo para executar o comando
                ProcessBuilder builder = new ProcessBuilder("cmd.exe", "/c", "net user /domain " + matricula + "  " + senhaAleatoria);
                builder.redirectErrorStream(true);
                Process process = builder.start();

                String meuEmail = "suasenhawindows@youtilitycenter.com.br";//email do destinatário ( o certo seria puxar diretamnete de um banco de dados)
                String minhaSenha = "T$ZZA1UjaS%3"; //senha do email( o certo seria puxar diretamnete de um banco de dados)
                
                EmailAttachment attachment = new EmailAttachment();

                //comentado caso resolva enviar anexo por email
                // attachment.setPath("C:\\users\\tecnico.danie\\documents\\noronhapontos\\" + mes + "-" + ano + "\\comprovantes\\" + nome_usuario + "\\" + dataFormatada + " - " + horas + ".txt");
                // attachment.setDisposition(EmailAttachment.ATTACHMENT);
                //  attachment.setDescription("Anexo");
                //  attachment.setName("dataFormatada" + " - " + horas + ".txt");
                try {

                    // Cria o objeto de e-mail multipart
                    MultiPartEmail emailSender = new MultiPartEmail();
                    emailSender.setDebug(true);
                    emailSender.setHostName("smtpdoseuprovedor");
                    emailSender.setAuthentication(meuEmail, minhaSenha);
                    emailSender.setSSLOnConnect(true);
                    emailSender.setSmtpPort(465);
                    emailSender.addTo(emailConsultor);
                    emailSender.setFrom(meuEmail);
                    
                    //modelo da mensagem que será enviada pelo email
                    emailSender.setSubject("Nova senha de login do Windows gerada em: " + dataFormatada);// assunto do email
                    emailSender.setMsg("Olá! \n"
                            + "\n"
                            + "Espero que esta mensagem encontre você bem. Gostaríamos de informar que sua senha do windows foi redefinida com sucesso. Abaixo, você encontrará sua nova senha:\n"
                            + "\n"
                            + "Senha: " + senhaAleatoria + "\n"
                            + "\n"
                            + "Caso tenha alguma dúvida entre em contato com seu supervisor. Estamos sempre aqui para ajudar.\n"
                            + "\n"
                            + "Atenciosamente,\n"
                            + "\n"
                            + "Departamento de Tecnologia da Informação");//mensagem ( o certo seria puxar diretamnete de um banco de dados)

                    // Adiciona o anexo ao e-mail
                    //emailSender.attach(attachment);
                    // Envia o e-mail
                    emailSender.send();
                    Cursor cursor2 = new Cursor(Cursor.HAND_CURSOR);
                    jButton1.setCursor(cursor2);
                    
 
                        JOptionPane.showMessageDialog(null, "<html> <h3>Senha enviada com sucesso para o email: <h3><html>\n \n" + "<html> <span style='color:blue;'>" + emailConsultor + "</span><br><br><html> Nova senha: " + senhaAleatoria, "E-mail enviado com sucesso!", JOptionPane.INFORMATION_MESSAGE);; 
                } catch (EmailException e) {
                    JOptionPane.showMessageDialog(null, "E-mail inválido! ");// + e.getMessage());

                }

            }// irá iniciar a criação de email
            else {
                JOptionPane.showMessageDialog(null, "Campos vazios ou o e-mail não pertence à (coloque o nome da sua empresa).", "Campos inválidos", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {

        }
    }

    // automoção do email que será enviada a senha
    private String gerarSenhaAleatoria() {
        final String caracteresPermitidos = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*()/;-.,][+";
        final int tamanhoSenha = 8;

        SecureRandom random = new SecureRandom();
        StringBuilder senha = new StringBuilder(tamanhoSenha);

        for (int i = 0; i < tamanhoSenha; i++) {
            int index = random.nextInt(caracteresPermitidos.length());
            senha.append(caracteresPermitidos.charAt(index));
        }

        return senha.toString();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
